#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.19050
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DemoService.Resource", IsApplication=true)]

namespace DemoService
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_new_event = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_play = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_star = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_warning = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int FeedItemContent_WebView = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int buttonChangeURl = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int buttonEditPrm = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int buttonEnter = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int buttonPopMenu = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int buttonSignIn = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int editTextAddUrlAddress = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int editTextAddUrlPrm = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int editTextAdminPass = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int editTextChangeURl = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int editTextCurrentURl = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int editTextLogin = 2131099649;
			
			// aapt resource value: 0x7f060013
			public const int editTextLoginPrm = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int editTextPassword = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int editTextPasswordPrm = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int editTextUrlAddress = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int editTextUrlPrm = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int itemCls = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int itemRef = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int itemSet = 2131099672;
			
			// aapt resource value: 0x7f06000f
			public const int listViewOwerview = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int textViewAdminPass = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int textViewChangeURl = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int textViewCurrentURl = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int textViewLogin = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textViewPassword = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textViewStatus = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChangeLogin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChangeURl = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FeedItemContent = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FeedItemOwerview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Parametrs = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int popup_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int callNotice = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int callServiceMethod = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int start = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int stop = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
